---
cache: ccache
dist: trusty
language: cpp
services: xvfb
sudo: required

matrix:
    fast_finish: true
    include:
        - env: BUILD_ENV=windows
          os: windows

before_install:
    - |
        CMAKE=cmake

        case "$BUILD_ENV" in
            mingw-w64 )
                ARG=MinGW-w64-x86_64
                CMAKE=/usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-cmake
            ;;
            mingw-w32 )
                ARG=MinGW-w64-i686
                CMAKE=/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake
            ;;
            windows )
                choco install msys2 pkgconfiglite
            ;;
        esac
    - |
        if [ "$BUILD_ENV" != libretro ]; then
            ./installdeps $ARG
            DIR=build
        else
            DIR=src/libretro
        fi

before_script:
    - |
        if [ -n "$ENABLE_SDL" ]; then
            CMAKE_ARGS="$CMAKE_ARGS -DENABLE_SDL=ON"
        fi

script:
    - mkdir -p -- "$DIR"
    - cd -- "$DIR"
    - if [ "$BUILD_ENV" != libretro ]; then $CMAKE $CMAKE_ARGS ..; fi
    - make
    - if [ "$BUILD_ENV" != libretro ]; then make install DESTDIR=/tmp/VBAM; fi
    - |
        if [ -n "$XVFB_RUN" ]; then
            xvfb-run -a ./$PRGNAM --help
        # TODO: --help crashes on OSX sometimes.
        #elif [ "$BUILD_ENV" = mac ]; then
        #    ./$PRGNAM.app/Contents/MacOS/$PRGNAM --help
        fi

env:
    global:
        - CMAKE_ARGS=""
        - ENABLE_SDL=1
        - MAKEFLAGS="-j2"
        - PRGNAM=visualboyadvance-m

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/b273e1f74f164855d115
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
